"""
The button sheet: every glyph the pad can show, on its own disc, in one picture.

Why it exists. The glyphs are generated by nine scripts and normalised by a tenth, and until this
sheet existed nobody could see the family at once: you looked at one button in the game, or at one
PNG in a folder. A sheet is how you catch the glyph that is heavier than its neighbours, the two
that read alike, the one still in the old vocabulary. It is also what an outside designer is given,
which is why it carries no text, no layout, no labels: only the shapes, at the size the thumb sees.

The discs are the game's own plates, not a drawn circle, and each glyph sits at the same fraction
of its disc as in the pad (79 of 128). So the sheet shows the real optical weight of each verb,
which is the whole point of `normalise-glyphs.py` and the only thing worth reviewing here.

Two families: the pad's action button draws dark ink on the gold plate, and the fixed buttons
(jump, glide, weapon, menu) draw white on the blue one.

Run: python3 tools/ui/build-button-sheet.py
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
UI = os.path.abspath(os.path.join(HERE, '../../assets/ui'))
OUT = os.path.abspath(os.path.join(HERE, '../../images/hud-buttons.png'))

DISC = 128                  # the plate, at the size the pad draws it
GLYPH = 79                  # and the glyph's share of it, same ratio as the pad
GAP = 34
MARGIN = 46
COLUMNS = 7
GROUND = (13, 26, 46, 255)  # the game's night blue, so the plates read as they do in play

# Ordered as the pad reveals them: the build verbs, then what you do with an item, then the
# owner's own actions, then the two animations, then the buttons that are always on screen.
BUTTONS = [
    ('primary-disc', 'encre-build'), ('primary-disc', 'encre-place'),
    ('primary-disc', 'encre-pickup'), ('primary-disc', 'encre-steal'),
    ('primary-disc', 'encre-collect'), ('primary-disc', 'encre-crate'),
    ('primary-disc', 'encre-smash'), ('primary-disc', 'encre-buy'),
    ('primary-disc', 'encre-outbid'), ('primary-disc', 'encre-fuse'),
    ('primary-disc', 'encre-up'), ('primary-disc', 'encre-lock'),
    ('primary-disc', 'encre-give'), ('primary-disc', 'encre-drop'),
    ('primary-disc', 'encre-recover'), ('primary-disc', 'encre-fire'),
    ('primary-disc', 'encre-build-raised'), ('primary-disc', 'encre-build-mid'),
    ('primary-disc', 'encre-smash-raised'), ('primary-disc', 'encre-smash-mid'),
    ('secondary-disc', 'icon-jump'), ('secondary-disc', 'icon-glide'),
    ('secondary-disc', 'icon-gun'), ('secondary-disc', 'icon-slap'),
    ('secondary-disc', 'icon-taser'), ('secondary-disc', 'icon-holster'),
    ('secondary-disc', 'icon-menu'), ('secondary-disc', 'icon-menu-alert'),
]


def load(name, size):
    return Image.open(os.path.join(UI, f'{name}.png')).convert('RGBA').resize(
        (size, size), Image.LANCZOS)


if __name__ == '__main__':
    rows = -(-len(BUTTONS) // COLUMNS)
    step = DISC + GAP
    sheet = Image.new('RGBA', (MARGIN * 2 + COLUMNS * DISC + (COLUMNS - 1) * GAP,
                               MARGIN * 2 + rows * DISC + (rows - 1) * GAP), GROUND)
    inset = (DISC - GLYPH) // 2
    for i, (plate, glyph) in enumerate(BUTTONS):
        x, y = MARGIN + (i % COLUMNS) * step, MARGIN + (i // COLUMNS) * step
        sheet.alpha_composite(load(plate, DISC), (x, y))
        sheet.alpha_composite(load(glyph, GLYPH), (x + inset, y + inset))
    sheet.convert('RGB').save(OUT, optimize=True)
    print(f'wrote {OUT} ({sheet.width}x{sheet.height}, {len(BUTTONS)} buttons)')
